# Project Name
TARGET = SpectralBlur

# Sources
CPP_SOURCES = SpectralBlur.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
# DAISYSP_DIR = ../../DaisySP
DAICSP_DIR = ../../DaisySP-LGPL

# OPT = -O0

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
